-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 10:00:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb1` ;

-- -----------------------------------------------------
-- Schema mydb1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb1` DEFAULT CHARACTER SET utf8 ;
USE `mydb1` ;

-- -----------------------------------------------------
-- Table `mydb1`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idequipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb1`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb1`.`resultados` (
  `idresultados` INT NOT NULL AUTO_INCREMENT,
  `idequipo` INT NOT NULL,
  PRIMARY KEY (`idresultados`, `idequipo`),
  INDEX `fk_resultados_equipo_idx` (`idequipo` ASC) VISIBLE,
  CONSTRAINT `fk_resultados_equipo`
    FOREIGN KEY (`idequipo`)
    REFERENCES `mydb1`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
